# Generated by Django 3.2.8 on 2021-11-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people_user', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescenter',
            name='vacc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vacc'),
        ),
        migrations.AddField(
            model_name='people',
            name='vacc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.vacc'),
        ),
    ]
